### ISSUE TITLE
event.skipWaiting();

### ISSUE THREAD

**Issue by jakearchibald** [delapuente/service-workers-101#1]
It's actually `self.skipWaiting()` - the method is on the global. It can also be called any time before activation, not just during install.

(this graphic is brilliant btw)

**Comment by delapuente** [comment]
Thanks @jakearchibald , I'm going to fix the font issue and all the others today. Any feedback is welcome and let's use the issue tracker to ask for additions (push and sync already in the scope!) and modifications.

**Comment by delapuente** [comment]
Fixed in latest master, can be a delay until the README.md image updates.
