### ISSUE TITLE
Font issue?

### ISSUE THREAD

**Issue by jakearchibald** [delapuente/service-workers-101#3]
The header of the image is displaying like this for me:

<img width="463" alt="screen shot 2015-11-02 at 17 39 16" src="https://cloud.githubusercontent.com/assets/93594/10887682/b207a00a-8188-11e5-8ecb-d2b67be5dc7f.png">

This is in Chrome 46 (the current stable version), although I'm on pretty shitty hotel wifi right now.

**Comment by marco-c** [comment]
Same here on Firefox Nightly (45).

**Comment by delapuente** [comment]
The font is [Fira Sans](https://www.mozilla.org/en-US/styleguide/products/firefox-os/typeface/) but I would want to embed it in the SVG or at least see if the default could be a _sans_ font.
